# Generated by Django 4.1.7 on 2023-05-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderSocial', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatars', upload_to=''),
        ),
    ]
