# Generated by Django 4.1.7 on 2023-05-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_rename_image_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ingredientes', models.CharField(max_length=50)),
                ('personas', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Itinerarios',
        ),
    ]
